### ISSUE TITLE
Assembleia

### ISSUE THREAD

**Issue by rodrigondec** [jerimumhs/Documentos#2]
# IMPORTANTE
Para reorganizar e aprimorar a **possibilidade** (se continuar do jeito que está, não vai rolar) de nosso funcionamento para o próximo ano, a assembléia precisa da participação em massa de todos os associados (inclusive gerentes de comunidades) e qualquer interessado.

As decições serão feitas com base em um votação dos associados ativos **PRESENTES**. Os associados que estão pendentes só poderão votar após a normalização de suas assinaturas.

É **crucial** que todos os **INTERESSADOS** e **participantes de alguma comunidade local** que utilize o JerimumHS participe.

## Data
Nossa assembleia será **28 de novembro**.

# Pautas para a assembléia:
- Permanência da casa
    - Possibilidade de outros lugares
- Definição de termos de uso e associados
- Transparência financeira

**Comment by gabrieldamazio** [comment]
### SUGESTÃO

O nosso espaço poderia ser dentro de alguns dos MALLs de Natal, garantindo segurança e praticidade para todos, como Mandacaru, Portugal Center e CCABSul. Vou pesquisar preços e disponibilidades por lá.

**Comment by fguisso** [comment]
### SUGESTÃO

Ainda estou recolhendo informações sobre como ficaria o funcionamento, valores e afins, mas um amgio do CuboHub Cowork, que fica no Seaway, poderia fazer algum combinado legal para termos uma estrutura legal lá.

Vou fazer um levantamento destas questões, caso alguém tenha alguma outra duvida, pode falar que eu ja vejo no levantamento:

- Valores, agua, luz, internet, espaço
- O porque do lugar?(geografico)
- Quais opções do espaço que facilitam nossa vida?
- Pontos fracos e pontos fortes do filme!
- O que podemos contribuir com o espaço?
- O que o espaço/ecosistema pode contribuir para nós?

**Comment by jozemaria** [comment]
> ### SUGESTÃO
> Ainda estou recolhendo informações sobre como ficaria o funcionamento, valores e afins, mas um amgio do CuboHub Cowork, que fica no Seaway, poderia fazer algum combinado legal para termos uma estrutura legal lá.
> 
> Vou fazer um levantamento destas questões, caso alguém tenha alguma outra duvida, pode falar que eu ja vejo no levantamento:
> 
> * Valores, agua, luz, internet, espaço
> * O porque do lugar?(geografico)
> * Quais opções do espaço que facilitam nossa vida?
> * Pontos fracos e pontos fortes do filme!
> * O que podemos contribuir com o espaço?
> * O que o espaço/ecosistema pode contribuir para nós?
> * Horários que poderiamos ficar presentes no local
> * Limites de pessoas no espaço

**Comment by jozemaria** [comment]
### Sugestão

Mais dois tópicos que acho válido para o @fguisso fazer o levantamento no CuboHub, caso desse certo o local.

> * Horário que poderíamos ficar presente no local 
> * Limite de pessoas no Espaço

**Comment by rodrigondec** [comment]
### Sugestão
Precisamos organizar nosso calendário oficial. Uma boa maneira de fazer acredito que seja utilizando um google calendar. Que nem por exemplo o [calendário do brejatech](https://calendar.google.com/calendar/embed?src=u256mrbrrp21l3g4e0hd8hs02g%40group.calendar.google.com&ctz=America%2FFortaleza)

> já criei a um tempo o [nosso calendário](https://calendar.google.com/calendar/embed?src=d1j29c27rc9hdil3gibe6ti5jc%40group.calendar.google.com&ctz=America%2FFortaleza)
